# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Bijoy Linux
tagline:          িবজয় হোক উন্মুক্ত
description:      "লিনাক্সে আসার পরে বেশিরভাগ বাঙালীর অসুবিধা হয় বাংলা লেখা নিয়ে। যেহেতু বেশিরভাগই বিজয়ে অভ্যস্ত এবং বিজয়ের লিনাক্সের ডকুমন্টেশনের অবস্থা খুবই খারাপ তাই কিছু ইন্সটলারসহ অ্যাড করলাম। আশা করি নতুনদের কাজে লাগবে। "
url:              https://github.com/bijoylinux/bijoy
baseurl:

author:
  name:           Mr. Bijoy
  url:            #

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.0
sidebar_home_link:  true

github:
  repo:             https://github.com/bijoylinux/bijoy
